const abbreviationsList = [
      { term: "ADLs", def: "Activities of Daily Living" },
      { term: "ADPIE", def: "Assessment, Diagnosis, Planning, Implementation, Evaluation" },
      { term: "AMI", def: "Acute Myocardial Infarction" },
      { term: "CNA", def: "Certified Nursing Assistant" },
      { term: "CNO", def: "Chief Nursing Officer" },
      { term: "COPD", def: "Chronic Obstructive Pulmonary Disease" },
      { term: "CP", def: "Critical Pathway" },
      { term: "DRG", def: "Diagnosis-Related Group" },
      { term: "EBP", def: "Evidence-Based Practice" },
      { term: "ED / ER", def: "Emergency Department / Emergency Room" },
      { term: "EHR", def: "Electronic Health Record" },
      { term: "HIPAA", def: "Health Insurance Portability and Accountability Act" },
      { term: "HMO", def: "Health Maintenance Organization" },
      { term: "ICU", def: "Intensive Care Unit" },
      { term: "IV", def: "Intravenous" },
      { term: "IVPB", def: "Intravenous Piggyback" },
      { term: "L&D", def: "Labor and Delivery" },
      { term: "LOS", def: "Length of Stay" },
      { term: "LPN", def: "Licensed Practical Nurse" },
      { term: "LVN", def: "Licensed Vocational Nurse" },
      { term: "MAN", def: "Master of Arts in Nursing" },
      { term: "MSW", def: "Medical Social Worker" },
      { term: "NANDA-I", def: "North American Nursing Diagnosis Association International" },
      { term: "NCLEX-RN", def: "National Council Licensure Examination for Registered Nurses" },
      { term: "NCM", def: "Nursing Care Management" },
      { term: "PACU", def: "Post-Anesthesia Care Unit" },
      { term: "PCS", def: "Patient Classification System" },
      { term: "PHI", def: "Protected Health Information" },
      { term: "PNLE", def: "Philippine Nursing Licensure Examination" },
      { term: "PO", def: "Per Os (By Mouth / Oral Administration)" },
      { term: "PRN", def: "Pro Re Nata (As Needed)" },
      { term: "PT", def: "Physical Therapy / Physical Therapist" },
      { term: "QI", def: "Quality Improvement" },
      { term: "RM", def: "Registered Midwife" },
      { term: "RN", def: "Registered Nurse" },
      { term: "SDOH", def: "Social Determinants of Health" },
      { term: "SMART", def: "Specific, Measurable, Attainable, Realistic, Time-Bound" },
      { term: "SpO2", def: "Peripheral Capillary Oxygen Saturation" },
      { term: "ST", def: "Speech Therapy / Speech-Language Pathologist" },
      { term: "TKA", def: "Total Knee Arthroplasty" },
      { term: "TPC", def: "Total Patient Care (Case Method)" },
      { term: "UAP", def: "Unlicensed Assistive Personnel" },
      { term: "VAP", def: "Ventilator-Associated Pneumonia" }
    ];
